version: '3.8'
services: 
    cypress:
        image: cypress-test
        build: 
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - ./cypress:${ROOT}/cypress
        environment:
            - ROOT=/cypress-test
        working_dir: ${ROOT}
        command: ["npm", "test"]
    
