version: 2.1
orbs:
  node: circleci/node@4.7
jobs:
  build:
    docker:
      - image: circleci/node:16.10
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y xvfb
      - node/test:
          pkg-manager: npm
workflows:
  sample:
    jobs:
      - build
