version: 2.1

orbs:
  node: circleci/node@4.7
  cypress: cypress-io/cypress@1.37.0

workflows:
  sample:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    executor: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Install dependencies
                command: npm install
            - cypress/install
            - cypress/run:
                browser: chrome
