version: 2.1
orbs:
  node: circleci/node@4.7
jobs:
  setup:
    executor:
      name: node/default
    steps:
      - run:
          name: Install dependencies
          command: sudo apt-get update && sudo apt-get install -y xvfb
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: npm test
workflows:
  sample:
    jobs:
      - setup
      - test:
          requires:
            - setup
