name: Schedule Action

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        env:
          CYPRESS_baseUrl: http://localhost:3000
        run: npx cypress run --record --key YOUR_RECORD_KEY

      - name: Send email with results if tests fail
        if: ${{ failure() }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.sendgrid.net
          server_port: 587
          username: ${{ secrets.SENDGRID_USERNAME }}
          password: ${{ secrets.SENDGRID_PASSWORD }}
          subject: Cypress test results - Failed
          to: your-email@example.com
          from: your-email@example.com
          body: The Cypress tests have failed.
