name: Schedule Action

on:
  schedule:
   - cron: '0 */11 * * *'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i

      - name: Run Cypress tests
        run: npm test

      - name: Upload HTML report
        uses: actions/upload-artifact@v2
        with:
          name: Cypress HTML Report
          path: /home/runner/work/UI-Automation-Cypress-POM/UI-Automation-Cypress-POM/mochawesome-report/mochawesome.html       

      - name: Send email with results if tests fail
        if: ${{ failure() }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SENDGRID_USERNAME }}
          password: ${{ secrets.SENDGRID_PASSWORD }}
          subject: Environment is down.
          to: sultan.parvez@dsinnovators.com
          from: noreply@dsinnovators.com
          body: One or mutiple env is down, details are attached below.
          attachments: |
            /home/runner/work/UI-Automation-Cypress-POM/UI-Automation-Cypress-POM/mochawesome-report/mochawesome.html

